/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteprincipal;

/**
 *
 * @author elias
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        caja_bienvenida = new javax.swing.JLabel();
        caja_descripcion = new javax.swing.JLabel();
        boton_estado = new javax.swing.JButton();
        boton_eliminar_cama = new javax.swing.JButton();
        boton_añadir_cama = new javax.swing.JButton();
        boton_desocupar_cama = new javax.swing.JButton();
        boton_ocupar_cama = new javax.swing.JButton();
        boton_registro = new javax.swing.JButton();
        boton_volver_atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setMinimumSize(new java.awt.Dimension(800, 600));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        caja_bienvenida.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        caja_bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caja_bienvenida.setText("Bienvenido");
        caja_bienvenida.setToolTipText("");
        caja_bienvenida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        caja_bienvenida.setMaximumSize(new java.awt.Dimension(150, 30));
        caja_bienvenida.setMinimumSize(new java.awt.Dimension(150, 30));
        bg.add(caja_bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 230, 40));

        caja_descripcion.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        caja_descripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caja_descripcion.setText("Consulte aquí lo que necesite");
        bg.add(caja_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 320, 20));

        boton_estado.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        boton_estado.setText("ESTADO HOSPITALES");
        boton_estado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_estado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_estadoActionPerformed(evt);
            }
        });
        bg.add(boton_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 160, 90));

        boton_eliminar_cama.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        boton_eliminar_cama.setText("ELIMINAR UNA CAMA UTI");
        boton_eliminar_cama.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_eliminar_cama.setName("boton_eliminar_cama"); // NOI18N
        boton_eliminar_cama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eliminar_camaActionPerformed(evt);
            }
        });
        bg.add(boton_eliminar_cama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, 90));

        boton_añadir_cama.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        boton_añadir_cama.setText("AÑADIR CAMA UTI");
        boton_añadir_cama.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_añadir_cama.setName("boton_añadir_cama"); // NOI18N
        boton_añadir_cama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_añadir_camaActionPerformed(evt);
            }
        });
        bg.add(boton_añadir_cama, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 160, 90));

        boton_desocupar_cama.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        boton_desocupar_cama.setText("DESOCUPAR CAMA UTI");
        boton_desocupar_cama.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_desocupar_cama.setMaximumSize(new java.awt.Dimension(127, 17));
        boton_desocupar_cama.setMinimumSize(new java.awt.Dimension(127, 17));
        boton_desocupar_cama.setPreferredSize(new java.awt.Dimension(127, 17));
        boton_desocupar_cama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_desocupar_camaActionPerformed(evt);
            }
        });
        bg.add(boton_desocupar_cama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 160, 90));

        boton_ocupar_cama.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        boton_ocupar_cama.setText("OCUPAR CAMA UTI");
        boton_ocupar_cama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ocupar_camaActionPerformed(evt);
            }
        });
        bg.add(boton_ocupar_cama, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 160, 90));

        boton_registro.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        boton_registro.setText("REGISTRO OPERACIONES");
        boton_registro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registroActionPerformed(evt);
            }
        });
        bg.add(boton_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 160, 90));

        boton_volver_atras.setText("Atrás");
        boton_volver_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volver_atrasActionPerformed(evt);
            }
        });
        bg.add(boton_volver_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_añadir_camaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_añadir_camaActionPerformed
        // TODO add your handling code here:
        Añadir a = new Añadir();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_boton_añadir_camaActionPerformed

    private void boton_ocupar_camaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ocupar_camaActionPerformed
        // TODO add your handling code here:
        Ocupar a = new Ocupar();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_boton_ocupar_camaActionPerformed

    private void boton_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_registroActionPerformed

    private void boton_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_estadoActionPerformed

    private void boton_desocupar_camaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_desocupar_camaActionPerformed
        // TODO add your handling code here:
        Desocupar a = new Desocupar();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_boton_desocupar_camaActionPerformed

    private void boton_eliminar_camaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eliminar_camaActionPerformed
        // TODO add your handling code here:
        Eliminar a = new Eliminar();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_boton_eliminar_camaActionPerformed

    private void boton_volver_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volver_atrasActionPerformed
        Principal a = new Principal();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_boton_volver_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton boton_añadir_cama;
    private javax.swing.JButton boton_desocupar_cama;
    private javax.swing.JButton boton_eliminar_cama;
    private javax.swing.JButton boton_estado;
    private javax.swing.JButton boton_ocupar_cama;
    private javax.swing.JButton boton_registro;
    private javax.swing.JButton boton_volver_atras;
    private javax.swing.JLabel caja_bienvenida;
    private javax.swing.JLabel caja_descripcion;
    // End of variables declaration//GEN-END:variables
}
